### PR TITLE
SvelteKit / Vite compatibility

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/lgarron/clipboard-polyfill/issues/143

### CODE REVIEW

**Comment by benmccann** [comment]
I would be totally fine with `"type": "module"` instead. I tested that in my project and it works for me

Putting a nested `package.json` sounds a little scary to me. I've never seen that done before and am not totally sure all the implications of it. I agree the `.esm.js` file extension looks nicer than `.mjs`, but it's all hidden from the end user, so I figured it wasn't a big deal to change it

**Comment by lgarron** [comment]
Is there a minimal dependent repro I use to test out a few possible options?

**Comment by benmccann** [comment]
It's not exactly a minimal repro, but should hopefully still get the job done. Here's the project where I encountered this:
```
git clone git@github.com:benmccann/attractions.git
cd attractions/docs
git checkout reproduction
npm install
npm run build
```

**Comment by benmccann** [comment]
Oops! Sorry. It's there now: https://github.com/benmccann/attractions/tree/reproduction

**Comment by lgarron** [comment]
Given that I'm [deprecating this library](https://github.com/lgarron/clipboard-polyfill#%EF%B8%8F%EF%B8%8F%EF%B8%8F-to-be-deprecated-%EF%B8%8F%EF%B8%8F%EF%B8%8F), I will close this for now.

This library has been unnecessary in modern browsers for well over a year, and I'd like to avoid any changes that are not specifically fixed for legacy compatibility.

**Pull request closed without merging**
