### PR TITLE
Build target with and without Promise polyfill

### LINKED ISSUE #79: Remove Promise polyfill
Instead of bringing in a Promise polyfill, this library should encourage users to bring their own if they need to support old browsers, but shouldn't make this assumption by itself.

In my case I do want that polyfill, but I'm already bringing my own, so this one would just unnecessarily increase my bundle size.

### PR DESCRIPTION
**Pull request by abraham**
Fixes #80 feedback and Fixes #79.

This adds an additional entrypoint for Webpack which includes the `es6-promise` auto polyfill. That should automatically polyfill Promise if it's not present. I don't have a browser to test the automaticness of it though.

```sh
make build-for-git
env PROD=true ./node_modules/.bin/webpack
ts-loader: Using typescript@2.5.3 and /Users/abraham/dev/clipboard-polyfill/tsconfig.json
Hash: 24f88df6cf199b800833
Version: webpack 3.6.0
Time: 1463ms
                        Asset       Size  Chunks             Chunk Names
clipboard-polyfill.promise.js    13.1 kB    0, 1  [emitted]  clipboard-polyfill.promise
        clipboard-polyfill.js    4.69 kB       1  [emitted]  clipboard-polyfill
      clipboard-polyfill.d.ts  543 bytes          [emitted]
                      DT.d.ts  250 bytes          [emitted]
   [0] ./clipboard-polyfill.ts 8.63 kB {0} {1} [built]
   [1] ./DT.ts 1.17 kB {0} {1} [built]
   [2] multi es6-promise/dist/es6-promise.auto.js ./clipboard-polyfill.ts 40 bytes {0} [built]
   [5] (webpack)/buildin/global.js 509 bytes {0} [built]
    + 3 hidden modules
git stage -f build/*.js build/*d.ts
```

### CODE REVIEW

**Comment by lgarron** [comment]
Thank you so much, this is perfect!

Just one thing: should `es6-promise` be moved from `dependencies` to `devDependencies` in `package.json`?

**Comment by abraham** [comment]
Technically  the `es6-promise` dependency is only needed during dev but I'd leave it in `dependencies` so that if it gets flagged for a security issue, developers are more correctly notified.

**Comment by lgarron** [comment]
> @lgarron does that sound reasonable or would you like es6-promise moved to devDependencies?

I've thought about this a bit, and I think I definitely prefer `devDependencies`
The vulnerability argument feels like it should be a good reason, but other `devDependencies` can also easily introduce vulnerabilities.

**Comment by lgarron** [comment]
(Apologies for the delay; I just got back from 2 weeks of traveling.)

**Pull request merged**
